$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$ImagesRoot = Join-Path $Root 'images'
$Output = Join-Path $Root 'assets\js\images.js'
$TempOutput = "$Output.tmp"
$ValidExt = @('.jpg','.jpeg','.png','.webp','.gif','.avif')

function Get-PhotoPaths([string]$FolderPath) {
    $result = New-Object System.Collections.Generic.List[string]
    if (-not (Test-Path -LiteralPath $FolderPath)) { return $result.ToArray() }
    $seen = @{}
    Get-ChildItem -LiteralPath $FolderPath -File | Sort-Object Name | ForEach-Object {
        $ext = $_.Extension.ToLowerInvariant(); $key = $_.Name.ToLowerInvariant()
        if (($ValidExt -contains $ext) -and (-not $seen.ContainsKey($key))) {
            $seen[$key] = $true
            $rel = $_.FullName.Substring($Root.Length + 1) -replace '\\','/'
            [void]$result.Add($rel)
        }
    }
    return $result.ToArray()
}
function Js([string]$Text){if($null -eq $Text){return '""'};$s=$Text.Replace('\','\\').Replace('"','\"').Replace("`r",'\r').Replace("`n",'\n');return '"'+$s+'"'}
function JsArray($Items){$q=@();foreach($item in @($Items)){$q+=(Js ([string]$item))};return '['+($q -join ',')+']'}
function Clean-EventWords([string]$text){$x=$text -replace '[_-]+',' ';$x=$x -replace '\s+',' ';return $x.Trim()}
function Expand-Year([int]$y){if($y -lt 100){if($y -lt 70){return 2000+$y}else{return 1900+$y}}return $y}
function Exif-Date([string]$path){
    try{
        Add-Type -AssemblyName System.Drawing -ErrorAction SilentlyContinue
        $img=[System.Drawing.Image]::FromFile($path)
        try{
            # DateTimeOriginal 0x9003, DateTimeDigitized 0x9004, DateTime 0x0132
            foreach($id in @(0x9003,0x9004,0x0132)){
                try{$p=$img.GetPropertyItem($id);$s=[System.Text.Encoding]::ASCII.GetString($p.Value).Trim([char]0);if($s -match '^(\d{4}):(\d{2}):(\d{2})'){return Get-Date -Year ([int]$Matches[1]) -Month ([int]$Matches[2]) -Day ([int]$Matches[3])}}catch{}
            }
        } finally {$img.Dispose()}
    }catch{}
    return $null
}
function Display-Title([string]$folder,[string[]]$photos,[string]$absoluteFolder){
    $raw=$folder
    # Recognizes 6 15 26, 6-15-26, 06_15_2026, 6.15.26 at the START of the folder.
    if($raw -match '^\s*(\d{1,2})[\s._-]+(\d{1,2})[\s._-]+(\d{2,4})(?:[\s._-]+(.*))?$'){
        $m=[int]$Matches[1];$d=[int]$Matches[2];$y=Expand-Year([int]$Matches[3]);$rest=Clean-EventWords $Matches[4]
        try{$date=Get-Date -Year $y -Month $m -Day $d;$prefix=$date.ToString('MM-dd-yyyy');if($rest){return "$prefix $rest"}return $prefix}catch{}
    }
    $clean=Clean-EventWords $raw
    if(@($photos).Count -gt 0){
        $firstName=[System.IO.Path]::GetFileName($photos[0]);$first=Join-Path $absoluteFolder $firstName;$dt=Exif-Date $first
        if($dt){return ($dt.ToString('MM-dd-yyyy')+' '+$clean).Trim()}
    }
    return $clean
}

$data=[ordered]@{}
foreach($category in @('landing','sports','portraits','events','other')){$data[$category]=@(Get-PhotoPaths (Join-Path $ImagesRoot $category))}
# Keep each portfolio image in only one sample category; landing may reuse portfolio images.
$globalSeen=@{}
foreach($category in @('sports','portraits','events','other')){$unique=@();foreach($photo in @($data[$category])){$name=[IO.Path]::GetFileName($photo).ToLowerInvariant();if(-not $globalSeen.ContainsKey($name)){$globalSeen[$name]=$true;$unique+=$photo}};$data[$category]=@($unique)}

$shootObjects=@();$recentRoot=Join-Path $ImagesRoot 'recent-shoots'
if(Test-Path -LiteralPath $recentRoot){
    Get-ChildItem -LiteralPath $recentRoot -Directory | Sort-Object Name -Descending | ForEach-Object {
        $photos=@(Get-PhotoPaths $_.FullName)
        if($photos.Count -gt 0){$title=Display-Title $_.Name $photos $_.FullName;$shootObjects += [pscustomobject]@{id=$_.Name;title=$title;photos=$photos}}
    }
}
$lines=New-Object Collections.Generic.List[string]
[void]$lines.Add('// Auto-generated by UPDATE_IMAGES.bat. Do not edit by hand.')
[void]$lines.Add('window.SITE_IMAGES = {};')
foreach($category in @('landing','sports','portraits','events','other')){[void]$lines.Add(('window.SITE_IMAGES['+(Js $category)+'] = '+(JsArray $data[$category])+';'))}
[void]$lines.Add('window.SITE_SHOOTS = [];')
foreach($shoot in $shootObjects){$entry='{id:'+(Js $shoot.id)+',title:'+(Js $shoot.title)+',photos:'+(JsArray $shoot.photos)+'}';[void]$lines.Add('window.SITE_SHOOTS.push('+$entry+');')}
$content=$lines -join "`r`n"
if($content -notmatch 'window\.SITE_IMAGES'){throw 'Generated manifest is missing SITE_IMAGES.'}
[IO.File]::WriteAllText($TempOutput,$content,[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $TempOutput -Destination $Output -Force
Write-Host '';Write-Host '31 ACTION photo list updated successfully.' -ForegroundColor Green
foreach($category in @('landing','sports','portraits','events','other')){Write-Host ("  {0,-10} {1,4} photos" -f $category,@($data[$category]).Count)}
Write-Host ("  Recent shoots: {0}" -f $shootObjects.Count)
foreach($shoot in $shootObjects){Write-Host ('    '+$shoot.title)}
Write-Host '';if(@($data['landing']).Count -lt 2){Write-Host 'NOTE: Add at least 2 photos to images\landing for a slideshow.' -ForegroundColor Yellow}
Write-Host 'Return to the browser and press Ctrl+F5 to refresh.' -ForegroundColor Cyan
